{% set name = "helics" %}
{% set version = "2.0.0" %}
{% set checksum = "aa1a7be9032d1e7ad886bced08b4e0e8d3ffaf13fa21d1239e91c47e8a9dd677" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GMLC-TDC/HELICS-src/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 2
  skip: True  # [linux or (win and py27)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - swig
    - ninja
  host:
    - python
    - pip
    - boost-cpp
    - zeromq
  run:
    - python
    - boost-cpp
    - zeromq

test:
  imports:
    - helics

about:
  home: https://github.com/GMLC-TDC/HELICS-src
  license: BSD
  license_file: LICENSE
  license_family: BSD
  summary: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: http://gmlc-tdc.github.io/HELICS-src/index.html
  dev_url: https://github.com/GMLC-TDC/HELICS-src

extra:
  recipe-maintainers:
    - kdheepak
