{% set name = "helics" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/GMLC-TDC/HELICS.git
  git_rev: v{{ version }}

build:
  number: 0
  skip: True  # [linux or (win and py27)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - swig
    - ninja
    - boost-cpp
    - zeromq
    - python
  host:
    - python
    - boost-cpp
    - zeromq
  run:
    - python
    - boost-cpp
    - zeromq

test:
  imports:
    - helics

about:
  home: https://github.com/GMLC-TDC/HELICS
  license: BSD
  license_file: LICENSE
  license_family: BSD
  summary: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
