{% set name = "helics" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GMLC-TDC/HELICS-src/archive/v{{ version }}.tar.gz
  sha256: 73e24a09d59ae201e750ac287ab5ceb52c275e4ba6077d47274a9fafc612f2b5

build:
  number: 2
  skip: True  # [linux or (win and py27)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - swig 3.*
    - ninja
  host:
    - python
    - pip
    - boost-cpp
    - zeromq
  run:
    - python
    - boost-cpp
    - zeromq

test:
  imports:
    - helics

about:
  home: https://github.com/GMLC-TDC/HELICS-src
  license: BSD
  license_file: LICENSE
  license_family: BSD
  summary: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: http://gmlc-tdc.github.io/HELICS-src/index.html
  dev_url: https://github.com/GMLC-TDC/HELICS-src

extra:
  recipe-maintainers:
    - kdheepak
