appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Cv/uxKHT0jKkms+tLS/alRPrA8mQTBjy1D5UFrorHAuA8x5WjjRLAV1G42Y+Udxkk2iGUExiE4T2QcOVujtoxeBXMyFS0k1d06Ubba8kJUlRUXf4Dk6IeQpzMGdrhb7qA1AtkdL+fQTtvb7AYuCPbFGf1PmGgLt69CYgKxD6OTEOF86pmcPXVITiEQnI5FFj1+WOJsGUU/X9UKm2JHDxU1ZK4MExaqsIr6ISR7pTSQ5WKal6dOuQpUejKjm2KCR8jmjs7BQKAQU68dFJ3wyjIJDNvUWVBUR2N4WIkd4i2PhJSR4RJ7G1YWxsaKOBNRl2xlLu/qQTHEuBxYytCtxmFBOjQsv4xs3+6GdKAo8xv7hvZkfj4xljb17s9lHJBZLmevnnX2ivBe+VuwdwohkeMMPRUQe3olBqoD2YMvRKkiuwfkfA4AqSPpwwbsWaYLqCAZiPJ7NbNta1BPe/xqv6igHZKPHH+/rQmzbvXJ9ujntUtkJ11a+FxylDbhPK9PF5YYYyGOBwrxW4NibiIEk+qqdoG6A1cJ1FOZv50MR0vSoA7/tbN+tggdoAM5omHQDORWFY/iTwqf1iySrHDvDiUCjb5NmFeV2yf+OpdKUnfJyWsNa3yjP7xP/Sm0rThkt9nMHWBj5esEztMEh0MB5dlJvZMuo5I0BXJluqkurEwOc=}
